"""Generate organic foliage SVG paths for the hero scene.

Draws lobed leaf blades and irregular canopy masses with Catmull-Rom
smoothing — curves, not polygons. Deterministic (seeded).

Run: python3 scripts/generate-foliage.py > src/components/scene/foliage.ts
"""
import math
import random

W, H = 1440, 720


def catmull(points, closed=False):
    """Catmull-Rom through points -> cubic bezier path data."""
    p = list(points)
    if closed:
        p = [p[-1]] + p + [p[0], p[1]]
    else:
        p = [p[0]] + p + [p[-1]]
    d = [f"M {p[1][0]:.1f} {p[1][1]:.1f}"]
    for i in range(1, len(p) - 2):
        p0, p1, p2, p3 = p[i - 1], p[i], p[i + 1], p[i + 2]
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        d.append(
            f"C {c1[0]:.1f} {c1[1]:.1f} {c2[0]:.1f} {c2[1]:.1f} {p2[0]:.1f} {p2[1]:.1f}"
        )
    if closed:
        d.append("Z")
    return " ".join(d)


def leaflet(L, Wd):
    """One pointed-oval leaflet from origin along +x."""
    return (f"M 0 0 Q {L*0.45:.1f} {-Wd/2:.1f} {L:.1f} 0 "
            f"Q {L*0.45:.1f} {Wd/2:.1f} 0 0 Z")


def frond(cx, cy, length, angle, pairs, rng):
    """A pinnate frond: rachis with paired leaflets. Reads unmistakably as
    foliage where a jittered blob outline does not."""
    parts = []
    deg = math.degrees(angle)
    for i in range(pairs):
        t = (i + 0.6) / pairs
        # Leaflets longest mid-frond, tapering to base and tip.
        L = length * 0.40 * math.sin(math.pi * (t ** 0.62)) * rng.uniform(0.82, 1.18)
        Wd = L * rng.uniform(0.20, 0.30)
        y = -length * t
        # Leaflets sweep forward more toward the tip.
        lean = 52 - 26 * t
        for sign in (1, -1):
            a = deg + sign * lean * rng.uniform(0.88, 1.12)
            parts.append(
                f'<g transform="translate({cx:.1f} {cy:.1f}) rotate({deg:.1f}) '
                f'translate(0 {y:.1f}) rotate({sign*lean*rng.uniform(0.88,1.12)-90:.1f})">'
                f'<path d="{leaflet(L, Wd)}"/></g>'
            )
    # Rachis.
    parts.append(
        f'<g transform="translate({cx:.1f} {cy:.1f}) rotate({deg:.1f})">'
        f'<path d="M -{length*0.012:.1f} 0 L {length*0.012:.1f} 0 '
        f'L {length*0.004:.1f} {-length:.1f} L {-length*0.004:.1f} {-length:.1f} Z"/></g>'
    )
    return "".join(parts)


def canopy(cx, cy, rx, ry, bumps, rng):
    """An irregular canopy mass — a blob, not a triangle."""
    pts = []
    for i in range(bumps):
        a = (i / bumps) * math.tau
        jitter = rng.uniform(0.62, 1.24)
        pts.append((cx + math.cos(a) * rx * jitter, cy + math.sin(a) * ry * jitter))
    return catmull(pts, closed=True)


def band(seed, kind, count, y, yvar, size, sizevar, spread=(0, W)):
    """A horizontal band of foliage elements."""
    rng = random.Random(seed)
    out = []
    for i in range(count):
        x = spread[0] + (spread[1] - spread[0]) * (i / max(1, count - 1))
        x += rng.uniform(-60, 60)
        cy = y + rng.uniform(-yvar, yvar)
        s = size * rng.uniform(1 - sizevar, 1 + sizevar)
        if kind == "leaf":
            out.append(
                frond(x, cy, s, rng.uniform(-0.55, 0.55),
                      rng.randint(7, 11), rng)
            )
        else:
            out.append(
                '<path d="%s"/>' % canopy(
                    x, cy, s * rng.uniform(0.8, 1.3), s * rng.uniform(0.45, 0.8),
                    rng.randint(9, 14), rng)
            )
    return out


LAYERS = {
    # Far canopy: soft irregular masses hanging from the top of frame.
    "CANOPY_FAR": band(101, "canopy", 13, 70, 40, 120, 0.38),
    # Distant treeline replaced by rolling canopy silhouette.
    "CANOPY_MID": band(202, "canopy", 11, 500, 35, 140, 0.34),
    # Midground: leaf forms start to read individually.
    "FOLIAGE_MID": band(303, "leaf", 22, 700, 45, 190, 0.36),
    # Near: big blades pushing in from the lower edge.
    "FOLIAGE_NEAR": band(404, "leaf", 15, 760, 55, 290, 0.34),
    # Foreground: oversized framing blades, mostly off-canvas.
    "FOLIAGE_FORE": band(505, "leaf", 10, 810, 60, 430, 0.30),
}

print("// Generated by scripts/generate-foliage.py — do not edit by hand.")
print("// Regenerate: python3 scripts/generate-foliage.py > src/components/scene/foliage.ts")
print()
print(f"export const FOLIAGE_VIEWBOX = {{ width: {W}, height: {H} }} as const;")
print()
for name, paths in LAYERS.items():
    print(f"export const {name}: string[] = [")
    for d in paths:
        # Single-quote SVG attributes so fragments embed in double-quoted TS.
        print('  "%s",' % d.replace('"', "'"))
    print("];")
    print()
