"""Generate SVG treeline paths for the hero scene.

Deterministic (seeded), so regenerating produces identical output.
Run: python3 scripts/generate-treeline.py > src/components/scene/treelines.ts
"""
import random

W = 1440


def fir(x, base, h, w):
    """One fir silhouette: a jagged triangle with branch notches."""
    steps = [(1.00, 0.00), (0.74, 0.28), (0.86, 0.31), (0.52, 0.57),
             (0.63, 0.60), (0.28, 0.82), (0.36, 0.84), (0.06, 0.97)]
    left = [(x - w * sx, base - h * sy) for sx, sy in steps]
    right = [(x + w * sx, base - h * sy) for sx, sy in reversed(steps)]
    pts = left + [(x, base - h)] + right
    return pts


def treeline(seed, count, hmin, hmax, wmin, wmax, base, jitter):
    rng = random.Random(seed)
    d = [f"M -40 {base + 60}", f"L -40 {base}"]
    step = (W + 80) / count
    for i in range(count):
        x = -40 + i * step + rng.uniform(-jitter, jitter)
        h = rng.uniform(hmin, hmax)
        w = rng.uniform(wmin, wmax)
        for px, py in fir(x, base, h, w):
            d.append(f"L {px:.1f} {py:.1f}")
    d.append(f"L {W + 40} {base}")
    d.append(f"L {W + 40} {base + 60}")
    d.append("Z")
    return " ".join(d)


LAYERS = [
    # name,        seed, count, hmin, hmax, wmin, wmax, base, jitter
    ("distant",     11,   78,    46,   96,   11,   20,   250,  5),
    ("mid",         23,   46,    92,  178,   19,   34,   300,  8),
    ("foreground",  37,   22,   190,  330,   38,   66,   400, 14),
]

print("// Generated by scripts/generate-treeline.py — do not edit by hand.")
print("// Regenerate: python3 scripts/generate-treeline.py > src/components/scene/treelines.ts")
print()
print("export const VIEWBOX = { width: %d, height: 420 } as const;" % W)
print()
for name, *args in LAYERS:
    print(f'export const {name.upper()}_TREELINE =')
    print(f'  "{treeline(*args)}";')
    print()
